name = "ChromDistABC"
uuid = "923bc923-a63b-4f49-899c-ec4e14400614"
authors = ["Hannes Becher"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
